
#Deployment info
appName: devops1-task
namespace: default 
replicaCount: 1

#Image info
image:
  repo: 815919245801.dkr.ecr.eu-west-3.amazonaws.com/flask-app
  tag: latest
  imagePullPolicy: IfNotPresent
  ports:
    containerPort: 5000

#Service info
Service:
  serviceName: task-service
  ports:
    protocol: TCP
    port: 5000

#Ingress info
Ingress:
  ingressName: devopstask-ingress
ingress:
  enabled: true


